#ifndef MOTOR_SERVO_H
#define MOTOR_SERVO_H

#include <stdint.h>

void inline door_motor_init(){
  #if(MOTOR_DRIVER_HR8833_COUNT == 1)
  CONCAT(PORT, MOTOR_DRIVER_HR8833_DIR_PORT) &= ~((1 << MOTOR_DRIVER_HR8833_L) | (1 << MOTOR_DRIVER_HR8833_R));
  CONCAT(DDR, MOTOR_DRIVER_HR8833_DIR_PORT) |= ((1 << MOTOR_DRIVER_HR8833_L) | (1 << MOTOR_DRIVER_HR8833_L));
  CONCAT(PORT, MOTOR_DRIVER_HR8833_ENABLE_PORT) &= ~(1 << MOTOR_DRIVER_HR8833_ENABLE);
  CONCAT(DDR, MOTOR_DRIVER_HR8833_ENABLE_PORT) |= (1 << MOTOR_DRIVER_HR8833_ENABLE);
  #else
  #error "Unsupported HR8833 MotorConfig"
  #endif
}

/*
  0 = stop
  1 = forward
  2 = backward
  everything else is invalid
*/
void inline door_set_motor(uint8_t value){
  if(value == 0){
    CONCAT(PORT, MOTOR_DRIVER_HR8833_DIR_PORT) &= ~((1 << MOTOR_DRIVER_HR8833_L) | (1 << MOTOR_DRIVER_HR8833_R));
    CONCAT(PORT, MOTOR_DRIVER_HR8833_ENABLE_PORT) &= ~(1 << MOTOR_DRIVER_HR8833_ENABLE);
  }
  else if (value == 1){
    CONCAT(PORT, MOTOR_DRIVER_HR8833_DIR_PORT) &= ~((1 << MOTOR_DRIVER_HR8833_L) | (1 << MOTOR_DRIVER_HR8833_R));
    CONCAT(PORT, MOTOR_DRIVER_HR8833_DIR_PORT) |= (1 << MOTOR_DRIVER_HR8833_L) ;
    CONCAT(PORT, MOTOR_DRIVER_HR8833_ENABLE_PORT) |= (1 << MOTOR_DRIVER_HR8833_ENABLE);
  }
  else if (value == 2){
    CONCAT(PORT, MOTOR_DRIVER_HR8833_DIR_PORT) &= ~((1 << MOTOR_DRIVER_HR8833_L) | (1 << MOTOR_DRIVER_HR8833_R));
    CONCAT(PORT, MOTOR_DRIVER_HR8833_DIR_PORT) |= (1 << MOTOR_DRIVER_HR8833_R) ;
    CONCAT(PORT, MOTOR_DRIVER_HR8833_ENABLE_PORT) |= (1 << MOTOR_DRIVER_HR8833_ENABLE);
  }
}


#endif /* MOTOR_SERVO_H */