#ifndef CONFIG_OBEN_H
#define CONFIG_OBEN_H
#include "common.h"


#define MOTOR_IS_DC

#define MOTOR_DRIVER_HR8833
#define MOTOR_DRIVER_HR8833_COUNT 1
#define KEY_MOTOR MOTOR_DRIVER_HR8833

#define MOTOR_DRIVER_HR8833_ENABLE_PORT C
#define MOTOR_DRIVER_HR8833_ENABLE 0

#define MOTOR_DRIVER_HR8833_DIR_PORT D
#define MOTOR_DRIVER_HR8833_L 2
#define MOTOR_DRIVER_HR8833_R 3



#endif /* CONFIG_OBEN_H */